"""empty message

Revision ID: 08f6cbaaf58c
Revises: 
Create Date: 2021-02-18 04:41:40.457700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f6cbaaf58c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Station',
    sa.Column('Id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('City', sa.String(length=255), nullable=True),
    sa.Column('RegionalOffice', sa.String(length=255), nullable=True),
    sa.Column('County', sa.String(length=255), nullable=True),
    sa.Column('ConnectDate', sa.Date(), nullable=True),
    sa.Column('DisconnectDate', sa.Date(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('IsEtoStation', sa.Boolean(), nullable=True),
    sa.Column('Elevation', sa.Integer(), nullable=True),
    sa.Column('GroundCover', sa.String(length=255), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('SitingDesc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Station')
    # ### end Alembic commands ###
