"""Remove QC values from Main tables

Revision ID: 5d5c3578f17f
Revises: 872b4df20550
Create Date: 2021-06-30 15:40:55.125255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '5d5c3578f17f'
down_revision = '872b4df20550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DailyMain', 'DayWindWnwQc')
    op.drop_column('DailyMain', 'DayRelHumMaxQc')
    op.drop_column('DailyMain', 'DayRelHumAvgQc')
    op.drop_column('DailyMain', 'DayWindSswQc')
    op.drop_column('DailyMain', 'DayAsceEtrQc')
    op.drop_column('DailyMain', 'DaySoilTmpAvgQc')
    op.drop_column('DailyMain', 'DayPrecipQc')
    op.drop_column('DailyMain', 'DayAirTmpMinQc')
    op.drop_column('DailyMain', 'DayWindSseQc')
    op.drop_column('DailyMain', 'DayWindRunQc')
    op.drop_column('DailyMain', 'DayEtoQc')
    op.drop_column('DailyMain', 'DaySoilTmpMaxQc')
    op.drop_column('DailyMain', 'DayAirTmpAvgQc')
    op.drop_column('DailyMain', 'DayVapPresAvgQc')
    op.drop_column('DailyMain', 'DayAirTmpMaxQc')
    op.drop_column('DailyMain', 'DayRelHumMinQc')
    op.drop_column('DailyMain', 'DayWindWswQc')
    op.drop_column('DailyMain', 'DayWindNneQc')
    op.drop_column('DailyMain', 'DayWindNnwQc')
    op.drop_column('DailyMain', 'DaySoilTmpMinQc')
    op.drop_column('DailyMain', 'DayAsceEtoQc')
    op.drop_column('DailyMain', 'DayWindEneQc')
    op.drop_column('DailyMain', 'DaySolRadNetQc')
    op.drop_column('DailyMain', 'DayDewPntQc')
    op.drop_column('DailyMain', 'DayWindEseQc')
    op.drop_column('DailyMain', 'DayWindSpdAvgQc')
    op.drop_column('DailyMain', 'DaySolRadAvgQc')
    op.drop_column('DailyMain', 'DayVapPresMaxQc')
    op.drop_column('HourlyMain', 'HlySolRadQc')
    op.drop_column('HourlyMain', 'HlyEtoQc')
    op.drop_column('HourlyMain', 'HlyAsceEtoQc')
    op.drop_column('HourlyMain', 'HlyRelHumQc')
    op.drop_column('HourlyMain', 'HlyAsceEtrQc')
    op.drop_column('HourlyMain', 'HlyDewPntQc')
    op.drop_column('HourlyMain', 'HlySoilTmpQc')
    op.drop_column('HourlyMain', 'HlyVapPresQc')
    op.drop_column('HourlyMain', 'HlyWindDirQc')
    op.drop_column('HourlyMain', 'HlyNetRadQc')
    op.drop_column('HourlyMain', 'HlyAirTmpQc')
    op.drop_column('HourlyMain', 'HlyResWindQc')
    op.drop_column('HourlyMain', 'HlyWindSpdQc')
    op.drop_column('HourlyMain', 'HlyPrecipQc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('HourlyMain', sa.Column('HlyPrecipQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyWindSpdQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyResWindQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyAirTmpQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyNetRadQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyWindDirQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyVapPresQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlySoilTmpQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyDewPntQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyAsceEtrQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyRelHumQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyAsceEtoQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyEtoQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('HourlyMain', sa.Column('HlySolRadQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayVapPresMaxQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DaySolRadAvgQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindSpdAvgQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindEseQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayDewPntQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DaySolRadNetQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindEneQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayAsceEtoQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DaySoilTmpMinQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindNnwQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindNneQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindWswQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayRelHumMinQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayAirTmpMaxQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayVapPresAvgQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayAirTmpAvgQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DaySoilTmpMaxQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayEtoQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindRunQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindSseQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayAirTmpMinQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayPrecipQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DaySoilTmpAvgQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayAsceEtrQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindSswQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayRelHumAvgQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayRelHumMaxQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindWnwQc', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
