"""empty message

Revision ID: b4241cfddd05
Revises: 08f6cbaaf58c
Create Date: 2021-02-18 05:06:43.282534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4241cfddd05'
down_revision = '08f6cbaaf58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sisters',
    sa.Column('StationId', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('SisterOneId', sa.Integer(), nullable=True),
    sa.Column('SisterTwoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SisterOneId'], ['Station.Id'], ),
    sa.ForeignKeyConstraint(['SisterTwoId'], ['Station.Id'], ),
    sa.ForeignKeyConstraint(['StationId'], ['Station.Id'], ),
    sa.PrimaryKeyConstraint('StationId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sisters')
    # ### end Alembic commands ###
