"""add qc values to main data tables

Revision ID: bac2555634e1
Revises: 5d5c3578f17f
Create Date: 2021-11-03 12:13:41.262228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'bac2555634e1'
down_revision = '5d5c3578f17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DailyMain', sa.Column('DayAirTmpAvgQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayAirTmpMaxQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayAirTmpMinQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayAsceEtoQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayAsceEtrQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayDewPntQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayEtoQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayPrecipQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayRelHumAvgQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayRelHumMaxQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayRelHumMinQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DaySoilTmpAvgQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DaySoilTmpMaxQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DaySoilTmpMinQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DaySolRadAvgQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DaySolRadNetQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayVapPresAvgQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayVapPresMaxQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindEneQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindEseQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindNneQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindNnwQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindRunQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindSpdAvgQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindSseQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindSswQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindWnwQc', sa.String(length=50), nullable=True))
    op.add_column('DailyMain', sa.Column('DayWindWswQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyAirTmpQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyAsceEtoQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyAsceEtrQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyDewPntQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyEtoQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyNetRadQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyPrecipQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyRelHumQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyResWindQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlySoilTmpQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlySolRadQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyVapPresQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyWindDirQc', sa.String(length=50), nullable=True))
    op.add_column('HourlyMain', sa.Column('HlyWindSpdQc', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('HourlyMain', 'HlyWindSpdQc')
    op.drop_column('HourlyMain', 'HlyWindDirQc')
    op.drop_column('HourlyMain', 'HlyVapPresQc')
    op.drop_column('HourlyMain', 'HlySolRadQc')
    op.drop_column('HourlyMain', 'HlySoilTmpQc')
    op.drop_column('HourlyMain', 'HlyResWindQc')
    op.drop_column('HourlyMain', 'HlyRelHumQc')
    op.drop_column('HourlyMain', 'HlyPrecipQc')
    op.drop_column('HourlyMain', 'HlyNetRadQc')
    op.drop_column('HourlyMain', 'HlyEtoQc')
    op.drop_column('HourlyMain', 'HlyDewPntQc')
    op.drop_column('HourlyMain', 'HlyAsceEtrQc')
    op.drop_column('HourlyMain', 'HlyAsceEtoQc')
    op.drop_column('HourlyMain', 'HlyAirTmpQc')
    op.drop_column('DailyMain', 'DayWindWswQc')
    op.drop_column('DailyMain', 'DayWindWnwQc')
    op.drop_column('DailyMain', 'DayWindSswQc')
    op.drop_column('DailyMain', 'DayWindSseQc')
    op.drop_column('DailyMain', 'DayWindSpdAvgQc')
    op.drop_column('DailyMain', 'DayWindRunQc')
    op.drop_column('DailyMain', 'DayWindNnwQc')
    op.drop_column('DailyMain', 'DayWindNneQc')
    op.drop_column('DailyMain', 'DayWindEseQc')
    op.drop_column('DailyMain', 'DayWindEneQc')
    op.drop_column('DailyMain', 'DayVapPresMaxQc')
    op.drop_column('DailyMain', 'DayVapPresAvgQc')
    op.drop_column('DailyMain', 'DaySolRadNetQc')
    op.drop_column('DailyMain', 'DaySolRadAvgQc')
    op.drop_column('DailyMain', 'DaySoilTmpMinQc')
    op.drop_column('DailyMain', 'DaySoilTmpMaxQc')
    op.drop_column('DailyMain', 'DaySoilTmpAvgQc')
    op.drop_column('DailyMain', 'DayRelHumMinQc')
    op.drop_column('DailyMain', 'DayRelHumMaxQc')
    op.drop_column('DailyMain', 'DayRelHumAvgQc')
    op.drop_column('DailyMain', 'DayPrecipQc')
    op.drop_column('DailyMain', 'DayEtoQc')
    op.drop_column('DailyMain', 'DayDewPntQc')
    op.drop_column('DailyMain', 'DayAsceEtrQc')
    op.drop_column('DailyMain', 'DayAsceEtoQc')
    op.drop_column('DailyMain', 'DayAirTmpMinQc')
    op.drop_column('DailyMain', 'DayAirTmpMaxQc')
    op.drop_column('DailyMain', 'DayAirTmpAvgQc')
    # ### end Alembic commands ###
